msm8937-common: Build vintf module instead of copying
error: VINTF metadata found in PRODUCT_COPY_FILES: vendor/xiaomi/msm8937-common/proprietary/vendor/etc/vintf/manifest/android.h
ardware.gnss@2.0-service-qti.xml:vendor/etc/vintf/manifest/android.hardware.gnss@2.0-service-qti.xml, use DEVICE_MANIFEST_FILE / DEVICE_MATRIX_FILE / vintf_
compatibility_matrix / vintf_fragments instead!.

ref: https://github.com/root2raj/vendor_xiaomi_whyred/commit/c1b3edd9684c6e6d0fbd53f36c158aeafd9274f0